FROM python:3.12-slim

WORKDIR /app

COPY deployment/app/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY deployment/app/app.py ./app.py

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]